version: '3.1'

networks:
  monitor-net:
    driver: bridge

services:

  postgresql:
    image: postgres:alpine
    environment:
      POSTGRES_DB: iotplatform
      POSTGRES_USER: iotplatform
      POSTGRES_PASSWORD: iotplatform
    networks:
      - monitor-net

  vuejs:
    build:
      context: .
      dockerfile: ./front-end/Dockerfile
    environment:
      HOST: 0.0.0.0
    networks:
      - monitor-net

  django:
    build:
      context: .
      dockerfile: ./back-end/Dockerfile
    depends_on:
      - postgresql
    links:
      - postgresql:postgresql
    command: >
      bash -c "python3 manage.py migrate --noinput
      && python3 manage.py runserver 0.0.0.0:8000"
    networks:
      - monitor-net

  nginx_tomcat:
    image: nginx
    volumes:
      - ./proxyConf:/etc/nginx/conf.d
    ports:
      - 443:443
      - 1871:1871 
    links:
      - django:django
      - vuejs:vuejs
    networks:
      - monitor-net