
- name: Downloading CentOS-7 Server Template
  command: wget http://centos.excellmedia.net/7/isos/x86_64/CentOS-7-x86_64-Minimal-1804.iso

- name:  Create the qemu centos img
  command: qemu-img create -f qcow2 centos7-minimal.qcow2 3G

- name: Extracting server Template
  command: mv /root/centos7-minimal.qcow2 /home/kvm/images/


- name: System preparation is running on Template
  command: virt-sysprep -a /home/kvm/images/centos7-minimal.qcow2

- name: provisioning Server
  command: virt-install -n {{ KVMHostname }}
           --ram 2048 \
           --vcpus 2 \
           --os-type linux \
           --os-variant rhel7 \
           --import \
           --disk path=/home/kvm/images/centos7-minimal.qcow2,device=disk,bus=virtio,format=qcow2 \
           --network bridge=br0 \
           --graphics none \
           --serial tcp,host=127.0.0.1:7001,mode=bind,protocol=telnet

- name: "Starting {{ KVMHostname }} Server"
  pause:
    seconds: 40

- name: Configuring {{ KVMHostname }}
  ignore_errors: yes
  expect:
    command: telnet 127.0.0.1 7001
    timeout: 30
    responses:
      "Escape character is": "root"
      "Password: ": "abc123+"
      "# ":              
        - /sbin/iptables -P INPUT ACCEPT 
        - /sbin/iptables -P FORWARD ACCEPT 
        - /sbin/iptables -P OUTPUT ACCEPT
        - exit
        - quit

- name: Enabling AutoStart on {{ KVMHostname }}
  command: virsh autostart {{ KVMHostname }}

- name: Applying Configuration Changes on {{ KVMHostname }}
  command: virsh reboot {{ KVMHostname }}